cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'go'
brew 'grc'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'wget'
brew 'yarn'

cask 'transmission'
cask 'hyper'
cask 'dropbox'
cask '1password'
cask 'bettertouchtool'
cask 'karabiner-elements'
cask 'spotify'
cask 'spacemonkey'
cask 'sublime-text3'
cask 'virtualbox'
cask 'vagrant'
cask 'hipchat'
cask 'steam'
cask 'phpstorm'
cask 'whatsapp'
cask 'telegram'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown '
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'