cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'blackfireio/homebrew-blackfire'
tap 'caskroom/fonts'

brew 'coreutils'
brew 'ack'
brew 'go'
brew 'grc'
brew 'node'
brew 'readline'
brew 'wget'
brew 'yarn'
brew 'nmap'
brew 'tree'
brew 'mas'
brew 'php@7.2'
brew 'composer'
brew 'nvm'
brew 'watchman'
brew 'bower'
brew 'ansible'
brew 'hub'

cask 'hyper'
cask '1password'
cask 'karabiner-elements'
cask 'spotify'
cask 'sublime-text'
cask 'virtualbox'
cask 'vagrant'
cask 'hipchat'
cask 'phpstorm'
cask 'teamviewer'
cask 'google-chrome'
cask 'aerial'
cask 'font-fira-code'
cask 'macdown'
cask 'atom'

# Quick look plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
