cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/php'
tap 'blackfireio/homebrew-blackfire'

brew 'coreutils'
brew 'ack'
brew 'go'
brew 'grc'
brew 'node'
brew 'readline'
brew 'wget'
brew 'yarn'
brew 'nmap'
brew 'youtube-dl'
brew 'tree'
brew 'mas'
brew 'php70'
brew 'homebrew/php/composer'
brew 'nvm'
brew 'watchman'
brew 'bower'
brew 'blackfire-agent'
brew 'ansible'

cask 'transmission'
cask 'hyper'
cask 'dropbox'
cask '1password'
cask 'bettertouchtool'
cask 'karabiner-elements'
# cask 'spotify'
cask 'sublime-text'
cask 'virtualbox'
cask 'vagrant'
cask 'hipchat'
cask 'steam'
cask 'phpstorm'
cask 'whatsapp'
cask 'telegram'
cask 'querious'
cask 'sketch'
cask 'the-unarchiver'
cask 'teamviewer'
cask 'mplayerx'
cask 'sip'
cask 'google-chrome'
cask 'aerial'

# Quick look plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
